### ISSUE TITLE
Label doesn't appear in new announcements!

### ISSUE THREAD

**Issue by messalas** [owncloud/notifications#119]
The label doesn't appear any more when I post a new announcement in the announcementcenter!!!

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** PHP Version 7.0.22-0ubuntu0.16.04.1

**ownCloud version:** 10.0.3.3

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** owncloud

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**Comment by messalas** [comment]
I checked it again today, and it the label is again back!..
I don't know why wasn't shown yesterday..

**Comment by messalas** [comment]
UPDATE:
I just added one more announcement and the label isn't shown.. ?
Under which circumstances, the label is shown?

**Comment by DeepDiver1975** [comment]
please use only on issue and answer questions - thx - https://github.com/owncloud/announcementcenter/issues/90#issuecomment-341921810
