### ISSUE TITLE
App type & activation

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/notifications#12]
Currently the app is marked as »Experimental« and not enabled by default.

If we want to ship this with 8.2 we should make it »Official« and make it enabled by default. cc @karlitschek @nickvergessen @tomneedham

**Comment by karlitschek** [comment]
agreed. @nickvergessen can yo add the enable by default tag to info.xml?

**Comment by nickvergessen** [comment]
Yes we can do that, once the UI is there. Until then I'd say the app is actually experimental.
But yes, we should change it on the release

**Comment by nickvergessen** [comment]
After working with Vincent on the Ajax stuff we discovered a problem which we might not be able to fix in time: https://github.com/owncloud/notifications/issues/18

My suggestion would be remove it from the ship list for 8.2 and finish it properly in the 20% time for 9.0

**Comment by nickvergessen** [comment]
cc @cmonteroluque

**Comment by jancborchardt** [comment]
Hm, so no Notifications for 8.2? : (

**Comment by nickvergessen** [comment]
Yeah thats what i would say atm.

**Comment by karlitschek** [comment]
We have to fix this. Please merge the current state for now and let's look into a fix for the issue tomorrow.
Thanks guys.

**Comment by nickvergessen** [comment]
We'd like to have a look at more then just one usecase, so it works for most apps, not just the one we have now.

Otherwise we run in all the issues we already know from our existing APIs again and end up with spagetthi code in a brand new app.

This feature/app was not planned and is just not yet done...

**Comment by karlitschek** [comment]
we discussed this today. this is not acceptable. i will setup a call tomorrow to discuss this.

**Comment by cmonteroluque** [comment]
@karlitschek I don't recall this being in the list of 8.2 deliverables. @MTRichards to confirm? I may be mistaken. However, if I am not, we have a ton of bugs to address for 8.2 (including @nickvergessen finishing firewall work that is late already). @karlitschek happy to talk about this.

**Comment by MTRichards** [comment]
Yep.  Was not in the initial list.

-- 
Matt Richards
VP Products & Markets 
ownCloud, inc.

**Comment by karlitschek** [comment]
But something we have put on the list in Berlin.
Let's discuss tomorrow in the call how to move forward.

**Comment by jancborchardt** [comment]
Some ideas, not concrete, only looking how we can move forward, base for discussion:

* we mark the app at least as »Approved« and auto-enable it
* we encourage app devs to hook in their apps with it, like we did with Activity
* when there are no notifications, we hide the icon entirely from the header. Cause otherwise it looks strange since we don't have a lot of notifications yet.

**Comment by jancborchardt** [comment]
But yeah, we should definitely male the Notification app part of 8.2 so devs can start using it. Because otherwise it will take another cycle …

**Comment by DeepDiver1975** [comment]
> But yeah, we should definitely male the Notification app part of 8.2 so devs can start using it. Because otherwise it will take another cycle …

To be honest this argument is lame .... we should not release something which is not yet optimal

**Comment by jancborchardt** [comment]
@DeepDiver1975 what do you think about the proposals in my first comment then instead of using the lame argument as a decoy? ;)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 what do you think about the proposals in my first comment then instead of using the lame argument as a decoy? ;)

I cannot judge over this whole thing - I'm totally out of this ... would need to get into this first.

**Comment by karlitschek** [comment]
O.K. The results of the discussion is:
- We delay the remote share accept dialog port to notification util 9.0
- The notification system itself is fully working and can/will be in 8.2
- The notification icon will be hidden when no app is using the system.
The necessary should be minimal and @nickvergessen will do it today.
I hope this works for everyone.

**Comment by cmonteroluque** [comment]
@nickvergessen status please? This was supposed to be minimal about a week ago...

**Comment by nickvergessen** [comment]
This was all addressed 8 days ago:
* Hide notification icon when there are no notifiers: https://github.com/owncloud/notifications/pull/25
* Disable remote sharing notifier: https://github.com/owncloud/core/pull/19087

The only question left open is:

should the app be in the experimental section, or not.
As per description of the section:
> Experimental apps are not checked for security issues, new or known to be unstable and under heavy development. 

3 out of this 4 things match:
* not checked for security issues
* new
* under heavy development

So I'd say we set `default_enable` and **not** set `shipped`, because otherwise the app is just marked as `Official` instead of `Experimental`.

But if @karlitschek and you @cmonteroluque think it should be `Official` instead of `Experimental` I will make a patch that adds both. Your call

**Comment by jancborchardt** [comment]
I would say it should at least be marked approved, no? `default_enable` should be there as well because otherwise it’s always disabled on update (right?) which is quite weird for such a »core« app.

**Comment by karlitschek** [comment]
it should be enabled b default as jan said. othereise no app will use it. experimental only exists for non shipped apps.

**Comment by nickvergessen** [comment]
Default enabled: https://github.com/owncloud/notifications/pull/28
Shipped flag: https://github.com/owncloud/core/pull/19328

The app is currently still listed as "experimental" due to a bug in core:
https://github.com/owncloud/core/pull/19337

**Comment by cmonteroluque** [comment]
thanks @nickvergessen
