### ISSUE TITLE
Button layout broken when not on files list

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/notifications#16]
# Files
![bildschirmfoto vom 2015-09-15 16 38 08](https://cloud.githubusercontent.com/assets/213943/9879577/4e3b12b8-5bc8-11e5-9cb4-593bf4c7024d.png)

# Personal
![bildschirmfoto vom 2015-09-15 16 38 13](https://cloud.githubusercontent.com/assets/213943/9879587/5a0d2c34-5bc8-11e5-892a-6847ed6689bf.png)

**Comment by PVince81** [comment]
Because notifications uses ".actions" which is also defined by files.css and not namespaces properly.
Ideally the notifications app should specify it's on ".actions" style.

**Comment by nickvergessen** [comment]
This is broken again @jancborchardt 

Files list:
![notifications-new](https://cloud.githubusercontent.com/assets/213943/9986736/832148fe-6040-11e5-9154-a072982164ff.png)

Personal settings:
![personlich_-_owncloud_-_2015-09-21_09 09 36](https://cloud.githubusercontent.com/assets/213943/9986737/88ee97f0-6040-11e5-8fb4-474b56fc1fc0.png)

**Comment by nickvergessen** [comment]
In order to easily test it, modfiy
[controller/endpointcontroller.php::get](https://github.com/owncloud/notifications/blob/master/controller/endpointcontroller.php#L68)
and add as a first line in the method:
```php
return [
	[
		'app' => 'testing',
		'user' => 'user',
		'timestamp' => time(),
		'object_type' => 'type',
		'object_id' => 1337,
		'subject' => 'I\'m a short subject',
		'message' => 'Maybe we need longer descriptions later, no usecase in mind at the moment',
		'link' => '/get/request/when/subject/or/message/is/clicked',
		'icon' => 'testing-app-icon',
		'actions' => [
			[
				'label' => 'Action',
				'icon' => 'testing-app-icon-action',
				'link' => '/post/request/sending',
				'type' => 'POST',
			],
			[
				'label' => 'No Action',
				'icon' => 'testing-app-icon-no',
				'link' => '/delete/request/sending',
				'type' => 'DELETE',
			],
		],
	]
];
```

**Comment by nickvergessen** [comment]
@jancborchardt please take care of this

**Comment by jancborchardt** [comment]
@nickvergessen the code you supplied above does not work for some reason. Can you help again? Or just give me the HTML code it spits out and where to place it.

cc @owncloud/designers @Henni @oparoz if someone of you wants t otake care of this as my vacation is about to start …

**Comment by nickvergessen** [comment]
hmpf, right the notification_id entry was missing:
```php
		$data = [
			[
				'notification_id' => 123,
				'app' => 'testing',
				'user' => 'user',
				'timestamp' => time(),
				'object_type' => 'type',
				'object_id' => 1337,
				'subject' => 'I\'m a short subject',
				'message' => 'Maybe we need longer descriptions later, no usecase in mind at the moment',
				'link' => '/get/request/when/subject/or/message/is/clicked',
				'icon' => 'testing-app-icon',
				'actions' => [
					[
						'label' => 'Action',
						'icon' => 'testing-app-icon-action',
						'link' => '/post/request/sending',
						'type' => 'POST',
					],
					[
						'label' => 'No Action',
						'icon' => 'testing-app-icon-no',
						'link' => '/delete/request/sending',
						'type' => 'DELETE',
					],
				],
			]
		];
		$response = new JSONResponse($data);
		return $response;
```

**Comment by jancborchardt** [comment]
@owncloud/designers @Henni @raghunayyar am on vacation, can someone of you take care of this? Most probably a simple float fix.

**Comment by cmonteroluque** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by karlitschek** [comment]
@PVince81

**Comment by PVince81** [comment]
PR is here https://github.com/owncloud/notifications/pull/37
