### ISSUE TITLE
occ notifications:generate command no longer working since email notification change

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/notifications#169]
@jvillafanez the code block in app.php you removed broke this.
I also question if sending notifications in other places (e.g. market app) is also broken?

THX

**Comment by guruz** [comment]
I can confirm that notifications works for me after switching my notifications app to something with https://github.com/owncloud/notifications/pull/171 merged. (it didn't work on friday, thanks for pointing me to https://github.com/owncloud/core/issues/31031 @tomneedham )
