### ISSUE TITLE
Translation is missing

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/notifications#183]
oC-version: 10.0.8
notification-version: 0.3.3
In the personal admin section I can´t read the settings in my language (german)

**Comment by DeepDiver1975** [comment]
translation sync job has to be setup ...

**Comment by PVince81** [comment]
@DeepDiver1975 assuming you assigned @tboerger to test shiny new tools to setup translations ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 assuming you assigned @tboerger to test shiny new tools to setup translations ?

we use drone now for the nightly translation stuff - @tboerger knows how to setup this .....

**Comment by tboerger** [comment]
For the apps we are currently still using jenkins, sync has been done at https://github.com/owncloud/notifications/commit/1af883cba2f746c5627848372b4bc4f0611df0ab without further changes.

**Comment by tboerger** [comment]
Done by https://jenkins.owncloud.com/view/translation/job/translation-app-notifications/1

**Comment by DeepDiver1975** [comment]
de just got pushed -> we need to backport translations before the release

**Comment by PVince81** [comment]
@DeepDiver1975 do you have your magic translation backporting script somewhere ?

**Comment by PVince81** [comment]
PR to add translations to stable10: https://github.com/owncloud/notifications/pull/233
