### ISSUE TITLE
php-cs-fixer

### ISSUE THREAD

**Issue by mmattel** [owncloud/notifications#184]
@DeepDiver1975 
Any plans to implement ``php-cs-fixer`` as we have in core ?

Part of https://github.com/owncloud/QA/issues/582

**Comment by mmattel** [comment]
@DeepDiver1975 Do you have an update on this?

**Comment by phil-davis** [comment]
- [ ] implement owncloud/coding-standard in ``vendor-bin``
- [ ] rename ``tests/Unit`` to ``tests/unit`` (case of ``Unit`` is non-standard)
- [ ] add ``test-acceptance-*`` to ``Makefile`` and use it from drone
- [ ] add ``test-php-unit`` to ```Makefile`` and use it from drone
- [ ] review the CI infrastructure and standardize anything else
