### ISSUE TITLE
Info shown in 'sharing file' notifications mail title should be more friendly

### ISSUE THREAD

**Issue by davitol** [owncloud/notifications#186]
Testing this PR https://github.com/owncloud/core/pull/30106 I have seen this behavior when someone receives a notification when a file has been shared with him.

![screen shot 2018-05-21 at 11 56 59](https://user-images.githubusercontent.com/10596560/40302264-d3e5f8ae-5cee-11e8-921f-a60fa44a22c7.png)

IMHO the info shown in the mail title related to share should be more friendly.

@pmaier1 please give us feedback here or options about what to show. 

If we consider that title is fine, then please close the ticket

**Comment by PVince81** [comment]
agreed with @pmaier1 that we need to fix this for the release, setting to "development".

input needed from @pmaier1 about what we want exactly (concept) and then think of solutions

**Comment by PVince81** [comment]
there's already a PR here https://github.com/owncloud/notifications/pull/187, screenshot requested

**Comment by jvillafanez** [comment]
waiting for feedback on the specific email subject

**Comment by PVince81** [comment]
pending backport PR tests: https://github.com/owncloud/notifications/pull/188

**Comment by PVince81** [comment]
code complete

- [  ] acceptance tests still pending merge: https://github.com/owncloud/notifications/pull/198
