### ISSUE TITLE
Order of accept/decline buttons in notification

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/notifications#21]
Just like in the modal, the accept button should be on the right. (Ideally with class .primary to make it stand out.)

Can you fix that @nickvergessen

**Comment by nickvergessen** [comment]
primary is not possible atm:
https://github.com/owncloud/notifications/issues/23

**Comment by jancborchardt** [comment]
Ok, that’s fine. But can you change the order so that the positive / accept action is on the right? Thanks!

**Comment by nickvergessen** [comment]
yes
