### ISSUE TITLE
jQuery Core 1.9 Upgrade Guide

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/notifications#214]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9
See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Minor

`.trigger()`

- [x] /js/app.js

`.ajax()`

- [x] /js/app.js

`.attr()`

- [x] /js/app.js

`.prop()`

- [x] /js/personal_settings.js

`.before()`

- [x] /js/app.js

`.appendTo()`

- [x] /js/notification.js

**Comment by felixheidecke** [comment]
Can't test `_onClickAction()` method as there is no `occ n:g` flag to trigger an action button. :-(
Let's just hope it works :sweat_smile:

**Comment by felixheidecke** [comment]
@PVince81 can we "hope" and call it a day here?

**Comment by PVince81** [comment]
you can test it with the action button for accepting a local or a federated share

for local share go to settings and untick "Automatically accept shares", then share something. The recipient will receive a notification.

**Comment by felixheidecke** [comment]
Aaaaand it works fine!
