### ISSUE TITLE
E-mail notifications 

### ISSUE THREAD

**Issue by Macpiket** [owncloud/notifications#219]
Steps to reproduce
1. Go to Settings -> General (Language is Dutch)
2. Select a different Mail Notification
3. If you click on Save (Opslaan) nothing happens.
![image010 1](https://user-images.githubusercontent.com/42067000/43649557-bf7b0a60-973d-11e8-82a8-8185737e7325.jpg)

Then Try in English:
1. Go to Settings -> General
2. Select a different Mail Notification
3. If you click on Saving and still nothing happens. However three dots show behind the word saving, so it looks like something is being saved, but nothing happens.
![schermafbeelding 2018-08-03 om 13 58 09](https://user-images.githubusercontent.com/42067000/43649550-bb114fd4-973d-11e8-8140-d03c63ff533d.png)

Expected behaviour
The preference should be saved

Actual behaviour
Nothing happens

Error from log
<img width="932" alt="screen shot 2018-08-03 at 14 06 55" src="https://user-images.githubusercontent.com/42067000/43649584-cc8df1e0-973d-11e8-8605-2e84a1b438c8.png">

Server configuration
**ownCloud version:** (see ownCloud admin page)
10.0.9

**Where did you install ownCloud from:**

**Comment by PVince81** [comment]
@Macpiket is the "PATCH" HTTP method disabled on your web server ?

**Comment by PVince81** [comment]
closing due to lack of feedback

**Comment by markholland83** [comment]
@PVince81 Thank you! This resolved our similar issue.

For other stumbling upon this issue. We allow the following methods:
`AllowMethods GET HEAD POST PROPFIND PUT MKCOL DELETE MOVE PROPPATCH OPTIONS LOCK UNLOCK REPORT PATCH`
