### ISSUE TITLE
Wrong URL-Link in Mail

### ISSUE THREAD

**Issue by Felix-C** [owncloud/notifications#295]
### Steps to reproduce
Create a new User on https://cloud.zonentalk.de/

### Expected behaviour
1. System sends internal Server Name as link in mails

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
on Univention Server

**Web server:**
Apache

**Database:**
MySQL
**PHP version:**
7
**ownCloud version:** (see ownCloud admin page)
10.2.1.4
**Where did you install ownCloud from:**
Univention
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
``No errors have been found.`

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
`
Could not open input file: occ
``

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by JanAckermann** [comment]
Closed via https://github.com/owncloud/notifications/pull/333
