### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by tomneedham** [owncloud/notifications#3]
@jancborchardt 

Right now this is the view in the nav bar when there are no notifications:
![screen shot 2015-09-02 at 22 16 30](https://cloud.githubusercontent.com/assets/660805/9644890/778d0ea8-51c0-11e5-86bc-e36560a71d6a.png)
and with:
![screen shot 2015-09-02 at 22 16 44](https://cloud.githubusercontent.com/assets/660805/9644893/7af8406c-51c0-11e5-9bb6-ee16f034bcb3.png)
When new notifications appear, and you had none previously it pulses like the apps nav does when you enable an app.

The draw looks like this:
![screen shot 2015-09-02 at 22 17 30](https://cloud.githubusercontent.com/assets/660805/9644880/70e90692-51c0-11e5-8568-f149e84515c4.png)

Additionally, on mobile, the draw fills the width:
![screen shot 2015-09-02 at 22 18 33](https://cloud.githubusercontent.com/assets/660805/9644910/91a0ac64-51c0-11e5-8db1-02ff429acb7f.png)

The notification draw is scrollable too.

There is a dismiss icon on hover of a notification:
![screen shot 2015-09-02 at 22 19 01](https://cloud.githubusercontent.com/assets/660805/9644929/a89dee0e-51c0-11e5-92a4-c42269aa42a6.png)

The draw slides down and up when you click on the icon.

Feel free to adjust / comment. This was just my first attempt at something. Obviously we'd love icons for apps, avatars for users etc but lets get the basics in there first :)

**Comment by tomneedham** [comment]
Also @nickvergessen @karlitschek

**Comment by jancborchardt** [comment]
Cool stuff already! Will improve on that. :)

**Comment by karlitschek** [comment]
yes. definitely super cool already. i think the icon might need improvements. :-) Looks a  bit similar to our current 'i' icon which is used for help.
Beside that just awesome :-)

**Comment by raimund-schluessler** [comment]
Great work so far!

One suggestion: Could we maybe show the number of notifications in the icon, e.g.as an additional number on the right top or replacing the "i" if there are notifications?

**Comment by MTRichards** [comment]
@raimund-schluessler you mean like the iOS "mail" icon with the red circle and a number in it indicating unread messages, or something?

**Comment by raimund-schluessler** [comment]
Yes, that's one option. Or we just replace the "i" in the middle with the number.

**Comment by jancborchardt** [comment]
I will redesign the icon and then think about if adding a number makes sense or not. Many notification systems do not use numbers since: a) it mostly doesn’t make a difference how many notifications there are and b) people don’t memorize the number so it has no value in judging if there are more from when looking at it last time.

**Comment by nickvergessen** [comment]
Lets close this and have separate issues for each thing that is still open
