### ISSUE TITLE
no workie with latest daily snapshot

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/notifications#31]
Not sure if you're up for bugreports, but with the latest snapshot, notifications gives me the error message "Failed to perform request for notifications". The notifications bell shows up (but empty):
![sidebar_4](https://cloud.githubusercontent.com/assets/551757/10159437/7aff20fc-6698-11e5-91b1-712b1550f64d.png)

The log shows nothing that seems relevant:
```
Error	core	can't remove app notifications. It is not installed.	2015-09-29T08:39:41+00:00
Warning	files_versions	-1 is not a valid value for maximal versions retention obligation. Check versions_retention_obligation in your config.php. Falling back to auto.	2015-09-29T08:33:03+00:00
Warning	core	Login failed: 'admin' (Remote IP: '::1')	2015-09-29T08:30:35+00:00
```
(the error was from me trying to remove the app in the web UI after I had removed it by hand, just a PEBKAC)

What can I do to help you debug this, or should I wait and grab a newer version?

**Comment by nickvergessen** [comment]
What's your list of apps?
And what version exactly is "latest snapshot"? (admin settings version section + potential download link)

For me the request behaves normally, gets a 404 (due to no notifiers) and then removes itself from the UI.

**Comment by jospoortvliet** [comment]
@nickvergessen no apps other than files, gallery, activities.

Version is daily snapshot of today, beta1 something, see https://owncloud.org/install/#testing-development - got the archive file there earlier today. Should be a git checkout of yesterday at the latest, I suppose.

**Comment by nickvergessen** [comment]
Well can you open the "Inspect element" view of your browser and tell the HTTP status code of the request to notifications

**Comment by jospoortvliet** [comment]
Turns out the last version of the snapshot is a week old. Once the snapshot is updated, I'll try again and let you know whazzup.

**Comment by jospoortvliet** [comment]
Ok, looks like this is a browser issue... Was using rekonq as firefox was fugly but looks like reK makes a mess anyhow so now I'm using Chromium and that seems to work fine...

**Comment by jospoortvliet** [comment]
after some playing around, I haven't received any notifications at all, so I'm still not sure if the notifications work.

The bell doesn't show up but I suspected it is automatically hidden when there are no notifications.

So I shared some files to one of my test users and logged in as that test user. No notifications.

Also, how are admins supposed to send notifications to users? I don't see anything in the admin panel.

**Comment by jospoortvliet** [comment]
trying to figure out what might be wrong, I see this error in the console:
![partners1](https://cloud.githubusercontent.com/assets/551757/10193117/61681d8a-6781-11e5-987a-3749d2453fa4.png)

**Comment by nickvergessen** [comment]
> after some playing around, I haven't received any notifications at all, so I'm still not sure if the notifications work.
> The bell doesn't show up but I suspected it is automatically hidden when there are no notifications.

There are no notifications in 8.2 with default apps:
See the comment at https://github.com/owncloud/notifications#no-notifications-sample

> Also, how are admins supposed to send notifications to users? I don't see anything in the admin panel.

That's not part of this app. It's planned for the announcements app thou https://github.com/nickv-oc/announcementcenter

So nothing wrong here.
Also the 404 is expected when there are no apps that generate notifications.

**Comment by jospoortvliet** [comment]
So there's nothing notification-related I can screenshot in 8.2... Ok.

**Comment by nickvergessen** [comment]
You can use the screenshots from the readme. Other then that you will have to wait for an app that adapts to it.

**Comment by jospoortvliet** [comment]
ok, cool - that gives us something nice to make videos and screenshots of in 9.0 ;-)

**Comment by nickvergessen** [comment]
I added notifications to the announcement center yesterday https://github.com/nickv-oc/announcementcenter
So you can use that for screenshots (if you clone it from github)
