### ISSUE TITLE
Add a registration system

### ISSUE THREAD

**Issue by oparoz** [owncloud/notifications#38]
I'd like to be notified when the updater apps finds a new version of Gallery+, but I don't want to be bombarded with notifications from other apps I don't use that much.

So, it would be great if I could be shown a list of providers and could untick the ones I don't want to hear about. Of course, some granularity could be added later on and a user could disable only some notifications from an app.

**Comment by karlitschek** [comment]
I suggest to add config options once this problem is real. So far I would like to try to not bombard the user in the first place

**Comment by nickvergessen** [comment]
> So far I would like to try to not bombard the user in the first place

yeah, bombarding is what the activity app is for. notifications on the other hand focuses on stuff that needs the attention of the user or even interaction.
