### ISSUE TITLE
[QA] notifications.svg could not be loaded when app is in apps-external

### ISSUE THREAD

**Issue by jnweiger** [owncloud/notifications#382]
Seen with notification-0.6.0-rc.1 and core 10.12.2

* I don't have a clear reproducer. Just saw that in the network tab of my firefox:
![grafik](https://github.com/owncloud/notifications/assets/1108546/adef8930-1f44-4f8d-a9a2-849f9793177f)

----

Seems it uses the /apps-external/ folder prefix as a web route prefix.
* https://oc10122-23-new-app-rcs-20230714.jw-qa.owncloud.works/apps-external/notifications/img/notifications.svg does not exist.
* https://oc10122-23-new-app-rcs-20230714.jw-qa.owncloud.works/apps/notifications/img/notifications.svg
would be correct.

Expected behaviour:
* The route prefix for apps is /apps/ regardless of the path, where the app is installed.

**Comment by jnweiger** [comment]
Sidenote: The notifiation.svg icon is difficult to see, when directly opened in a browser, it is a white bell on transparent background. I am adding gray manually:

![grafik](https://github.com/owncloud/notifications/assets/1108546/571aa4e0-77d4-432e-83fc-181662330c8a)

**Comment by pako81** [comment]
Cannot reproduce it: in my tests the path to notifications.svg is resolved correctly in both cases, when the notifications app is installed under `apps` as well as under `apps-external`. Tested on 10.12.2 + notifications 0.6.0rc2.

So in your case the app is actually installed under `apps`, correct? Because the issue title seems to suggest differently.

**Comment by jnweiger** [comment]
It was installed in the /apps-external/ folder. I am confused by the mapping to web routes. Should apps in apps-external have a configured web route of /apps-external/ in my config.php
My expected behaviour was wrong. Sorry for this.

Cannot reproduce either. Closing.
