### ISSUE TITLE
OCS API for Clients

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/notifications#43]
We need to transform this call to OCS: https://github.com/owncloud/notifications/wiki/Reading-and-deleting-notifications-as-a-Client#getting-the-notifications-of-a-user

- add a call to get a single notification
- use ISO date - no timestamp
- document etag behavior
- remove icon stuff

**Comment by nickvergessen** [comment]
> use ISO date - no timestamp

I assume you mean `date('c')` which is `2004-02-12T15:19:21+00:00` as per http://php.net/manual/en/function.date.php

**Comment by DeepDiver1975** [comment]
Would it make sense to have a PUT/POST operation to allow clients to push a notification?

@karlitschek @nickvergessen

**Comment by nickvergessen** [comment]
Well surely it would be nice in the perfect world. But atm I can't see something useful and looking at my schedule that might be something for later (9.x with x > 0)?

**Comment by DeepDiver1975** [comment]
> But atm I can't see something useful

I can at least see the need for this when writing integration tests @SergioBertolinSG 



> looking at my schedule that might be something

Happy to help out :wink:

**Comment by nickvergessen** [comment]
Discussion moved to #45
