### ISSUE TITLE
Adding behat integration tests for the OCS API

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/notifications#45]
- [x] @nickvergessen Write OCS endpoint for "if debug === true" to add notifications for app "testing*"
- [x] @nickvergessen Write notification notifier for "if debug === true" to parse notifications for app "testing*"
- [ ] @SergioBertolinSG Write tests to read and delete notifications

**Comment by nickvergessen** [comment]
- [ ] @nickvergessen Write OCS endpoint for "if debug === true" to add notifications for app "testing*"
- [ ] @nickvergessen Write notification notifier for "if debug === true" to parse notifications for app "testing*"
- [ ] @SergioBertolinSG Write tests to read and delete notifications
