### ISSUE TITLE
Icon doesnt update when notification appears while page is open

### ISSUE THREAD

**Issue by tomneedham** [owncloud/notifications#60]
Also the div#emptycontent is still present which looks strange
![screen shot 2016-02-04 at 16 22 41](https://cloud.githubusercontent.com/assets/660805/12821490/8a1a3d2e-cb5b-11e5-91a7-73342a633b6f.png)

**Comment by tomneedham** [comment]
Only happens in safari for some reason.

**Comment by nickvergessen** [comment]
@tomneedham any chance you can fix this at some point?

**Comment by tomneedham** [comment]
Yeah will do, just stuck it here so I dont forget.

**Comment by nickvergessen** [comment]
Have this as well, it happens when there have not been notifications initially but on polling there are some

**Comment by nickvergessen** [comment]
btw for lazy testing add:
```php
		return new \OC_OCS_Result([]);
		return new \OC_OCS_Result(json_decode('[{"notification_id":1,"app":"files_sharing","user":"admin","datetime":"2016-02-10T09:36:33+00:00","object_type":"remote_share","object_id":"1","subject":"You received \"\/test\" as a remote share from test1@localhost\/ownCloud\/master\/core","message":"","link":"","actions":[{"label":"Decline","link":"http:\/\/localhost\/ownCloud\/master\/core\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares\/pending\/1","type":"DELETE","primary":false},{"label":"Accept","link":"http:\/\/localhost\/ownCloud\/master\/core\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares\/pending\/1","type":"POST","primary":true}]}]', true));
```
as first line in https://github.com/owncloud/notifications/blob/c478791eefeff450b37be3d7bd44442a570dfa05/controller/endpointcontroller.php#L71-L71

**Comment by tomneedham** [comment]
Ah ideal!
