### ISSUE TITLE
Notifications icon shows by default in top bar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/notifications#65]
Since some time, the notifications icon shows by default in the top bar. Even though there are no notifications.

When there are no notifications, there is no need for the icon to show. @nickvergessen

**Comment by nickvergessen** [comment]
This is because we now have something that could show up: federated shares.
I think it's good to show the icon when something could show up, so the users get trained and know that it exists. It also helps app developers to get to know it and maybe add the functionality into their app...
Otherwise it never shows up when you don't receive a federated share, so how should they know?

**Comment by jancborchardt** [comment]
> Otherwise it never shows up when you don't receive a federated share, so how should they know?

When you do not receive a federated share, then it’s totally fine if it never shows up. If we want to advertise stuff to developers then we should do that, and not push it out to every single user. Especially not where space is so valuable such as in the top bar.

Sorry but at the moment the cases where actually notifications will show up there are so few that it doesn’t warrant showing a yet unneeded icon for an empty dropdown the whole time.

cc @karlitschek @owncloud/designers

**Comment by karlitschek** [comment]
No strong opinions here from me. I can see the point that we shouldn't show an icon if it is of no use. On the other side websites like Facebook and Google+ show an notification icon even if nothing is there.
So both is fine with me.

**Comment by jancborchardt** [comment]
Yeah, I was thinking about the other websites as well. But they definitely have more cases where notifications are shown.

So as of now I would still say we should only show the icon when there are notifications. Once there are more cases where there can be notifications, we could show it permanently. We can revisit that for 9.2 or so.
