### ISSUE TITLE
Notification: Failed to perform request for notifications

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/notifications#67]
My computer being idle for about 5 minutes, suddenly the yellow notification »Failed to perform request for notifications« appeared in the header.

This seems like an error completely irrelevant to users and should rather be in the console log / server error log than be put out directly. cc @nickvergessen @PVince81

**Comment by raimund-schluessler** [comment]
This might be unrelated, but:

I saw the same yellow notification about a failed request for notifications and soon afterwards my server behaved weird. It then only showed
```
Interner Serverfehler
Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.
```
After a reboot it now seems to work again. I can't dig any further at the moment as I am not at home. I will post more information if I find any in the logs.

**Comment by raimund-schluessler** [comment]
Maybe related to the lead day ;)

**Comment by nickvergessen** [comment]
Well the message is shown, when the request failed.
This is user information so he knows that the notification app will not show notifications.

Would be nice if you can have a look at the network tab next time this happens so we know what went wrong.

I assume 401 no auth at the moment. I will check if that is the case and then see if we can handle this better

**Comment by jancborchardt** [comment]
This is definitely not something to show to users. It’s an admin thing if at all. And it should show in the error log, not as a yellow notification. @nickvergessen 

cc @DeepDiver1975 @owncloud/designers

**Comment by nickvergessen** [comment]
So you dont want to tell the users that the app doesnt work atm?

**Comment by jancborchardt** [comment]
@nickvergessen exactly. Cause mostly this message just comes up in some timeout scenario, and the message offers no help how to fix it, and actually users can’t do anything to fix it anyway. It’s nothing which should be shown to them.
