### ISSUE TITLE
remote-share notification: Add "view in browser" link

### ISSUE THREAD

**Issue by dragotin** [owncloud/notifications#72]
It would be cool if the user could preview the contents of the remote share before he accepts it to decide if she really wants it.

The web client could open the link that shows its content in a new window, the desktop- or mobile clients should open a browser window.

**Comment by nickvergessen** [comment]
https://github.com/owncloud/notifications/blob/master/docs/ocs-endpoint-v1.md#notification-element
please see if `link` is empty. If it is not, you can use that link (web UI links the subject to that page when given).

Apart from that the notification app and API doesn't know any context, so no previewing etc is possible or in scope of this app/api/functionality.

**Comment by dragotin** [comment]
@nickvergessen the link is empty.  Can you please forward this problem to the dev who can solve it, ie. push the link info from sharing to the notification api? Thanks. This is not solved, so no need to close.

**Comment by nickvergessen** [comment]
This is solved in terms of notification app/API/functionality and a problem of sharing/federated-sharing

A list of "shares to accept/decline" is part of https://github.com/owncloud/core/issues/19153.

**Comment by nickvergessen** [comment]
Also see https://github.com/owncloud/core/issues/13495
