### ISSUE TITLE
What is an appropriate poll interval?

### ISSUE THREAD

**Issue by tomneedham** [owncloud/notifications#8]
30 seconds?

**Comment by karlitschek** [comment]
i think 30s sounds good

**Comment by nickvergessen** [comment]
Well currently it is only used by the remote sharing, for that I'd say 5minutes would be enough as well.
On the other side, to make it more powerful something like 30-60 secs sounds good to me.

However, we have to remember that changing the app page does a hard refresh and therefor ends up in a new poll with new 30 sec. So unless you stay on the same page, the polling doesn't really matter a lot.

**Comment by nickvergessen** [comment]
Set it to 30secs in #10
