### ISSUE TITLE
Subscribe email notifications from certain apps

### ISSUE THREAD

**Issue by pellaeon** [owncloud/notifications#9]
User can choose to subscribe email notifications from certain apps, so that when the app sends a notification, a email is sent to the user.

This would be useful for my registration app https://github.com/pellaeon/registration , as @jancborchardt suggested me to hook it up with notifications app.

**Comment by nickvergessen** [comment]
Does the action require user interaction?

**Comment by pellaeon** [comment]
I think by default users shouldn't be email subscribed to any notification, only when user explicitly says he/she wants to email subscribe we do that.

BTW, the use case for Registration app is when a new user registers, we send a email/notification to admins.

**Comment by nickvergessen** [comment]
Closing as per https://owncloud.org/blog/about-activities-and-notifications-in-owncloud/

**Comment by nickvergessen** [comment]
We might come back to this, if the plan shows to be unsuccessful, but then we can also reopen the issue.
