### ISSUE TITLE
Notification icon always hidden, can't get any notifications

### ISSUE THREAD

**Issue by nCr78** [owncloud/notifications#92]
The owncloud version I'm running is 9.1.4 on apache 2.4.18 on Ubuntu 16.04.2 LTS. The notifications icon seems to be missing and I get no errors/warnings in the console of FF/Chrome browser or the owncloud admin page.

I tried disabling and re-enabling it from the settings but nothing happened except a message appearing upon disabling notifications, saying "Failed to request notifications".

Is there anything I should have configured in my config.php? It seems others have reported this issue before, but haven't mentioned here. https://central.owncloud.org/t/notification-icon-missing/4398/5

**Comment by DeepDiver1975** [comment]
Can you please open the network console and look out for the request which tries to request the notifications. I'd like to see the request and the response. THX

**Comment by DeepDiver1975** [comment]
see https://central.owncloud.org/t/notification-icon-missing/4398/8?u=deepdiver1975

@nCr78 are you execution cron often enough?

**Comment by DeepDiver1975** [comment]
no feedback -> close
