### ISSUE TITLE
Transactional File Locking

### ISSUE THREAD

**Issue by jjooei** [owncloud/notifications#96]
### Steps to reproduce
1. Upgrade to owncloud 10.0 (by Softaculous)
2. After the upgrade read the red lines in the Security & setup warnings
3.

### Expected behaviour
No transactional file locking errror/warning

### Actual behaviour
The red warning will be shown:
--
Transactional file locking should be configured to use memory-based locking, not the default slow database-based locking.
--

### Server configuration
**Operating system**:
Debian 3.2.65-1+deb7u1 x86_64

**Web server:**
Apache

**Database:**
mysql

**PHP version:**
5.6.10

**ownCloud version:** (see ownCloud admin page)
10.0.0.12

**Where did you install ownCloud from:**
Softaculous installation script (at provider)

**Signing status (ownCloud 9.0 and above):**
(red) Some files have not passed the integrity check. Further information on how to resolve this issue can be found in our documentation.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
a lot, but for sure "File Locking app" isn't listed (neither as enabled nor as disabled)

The Administration Manual says:
--
Transactional file locking is in ownCloud core, and replaces the old File Locking app. The File Locking app has been removed from ownCloud in version 8.2.1. If your ownCloud server still has the File Locking app, you must visit your Apps page to verify that it is disabled; the File Locking app and Transactional File Locking cannot both operate at the same time.
--
The File Locking app is not listed there, but the solution for the warning says, the (not running) app shall be disabled => something is wrong there!

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => 314e4e893220f5cbd7f57c8dfd5e72c9cf9cd6696beecda47d0906478fe35a02608173757189dd10bb56015a0a077dc40eea5f5d2a9561b87464aa9a7c6fa52e
                            [current] => 9dec3819a40c97c21856a6976250c255cdc5feedc61eee02d8c918699a61060b7cb96bf2877548914a569413bf8d668cf354664e1f223af7dd06b995ad884ae6
                        )

                )

        )

)
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
Please follow the description at the end of that page - it explains on how to setup file locking properly
https://doc.owncloud.org/server/10.0/admin_manual/configuration_files/files_locking_transactional.html

![bildschirmfoto von 2017-05-02 11-39-37](https://cloud.githubusercontent.com/assets/1005065/25612729/0be2f6c2-2f2c-11e7-8955-7dbcfeb112c5.png)

**Comment by jjooei** [comment]
The problem is not to find the documentation for this issue (which I cannot use, since I use, since my owncloud is at a provider), but the fact, that I always used a default installation for new releases.

You wite in the docu:
The File Locking app has been removed from ownCloud in version 8.2.1.

I used also versions 9.x without receiving this Security & setiup warning (Transactional file locking should be configured to use memory-based locking, not the default slow database-based locking). Why appear the warning just now? The File Locking app is not there.

**Comment by DeepDiver1975** [comment]
file locking app is only one part of the story. you are not using redis for file locking - this is why you get this warning.

**Comment by jjooei** [comment]
redis cannot be installed on my account (shared hosting).

**Comment by Rohitsupe** [comment]
I am also facing the same problem ?

**Comment by vascowhite** [comment]
https://doc.owncloud.org/server/10.0/admin_manual/configuration_files/files_locking_transactional.html

404 not found.

**Comment by DeepDiver1975** [comment]
https://doc.owncloud.org/server/10.0/admin_manual/configuration/files/files_locking_transactional.html

**Comment by jjooei** [comment]
What up? What has this to do with the original question?


Viele Grüße / Best regards,
Dr. Jozsef Ferincz



2017-07-19 10:49 GMT+02:00 Thomas Müller <notifications@github.com>:

**Comment by jjooei** [comment]
what's up?


Viele Grüße / Best regards,
Dr. Jozsef Ferincz



2017-07-18 18:32 GMT+02:00 Paul White <notifications@github.com>:

**Comment by DeepDiver1975** [comment]
> redis cannot be installed on my account (shared hosting).

then you can perfectly live with the database backend for files locking - not the fastest solution but work in a small setup .

there is no issue.

**Comment by jjooei** [comment]
but the software shows it as issue! that's the point!


Viele Grüße / Best regards,
Dr. Jozsef Ferincz



2017-07-19 11:15 GMT+02:00 Thomas Müller <notifications@github.com>:

**Comment by XDavidT** [comment]
So, there is a solution for that ?
I'm facing the issue also...
